name: my-workflow
on: push
jobs:
  deploy:
      # needs: build
      name: deploy to github
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: Set up JDK 17
           uses: actions/setup-java@v1
           with:
             java-version: '16'
             distribution: 'adopt'
             cache: maven
         - name: Build with Maven
           run: mvn package
         - name: Step 3 - Use the Upload Artifact GitHub Action
           uses: actions/upload-artifact@v2
           with: 
             name: my artifact
             path: target/*.jar
